# PLACEHOLDER- this is not really developed yet. could keep separate from community summary if I want to look at, say, seasonal patterns by station. sparkline would be super cool

In [16]:
#!pip install pyarrow

In [17]:
import pandas as pd

# Summarize by Station

In [18]:
df_stations = pd.read_csv('../data/02-prepped/stations-2023-02-to-2024-01.csv')

In [29]:
df_stations['pct_january']=100*12*df_stations['rides_january']/df_stations['rides_all']
df_stations['pct_jan1416']=100*12*df_stations['rides_jan14_16']/df_stations['rides_all']

In [30]:
df_stations

,start_station_name,rides_all,rides_january,rides_jan14_16,first_ride,last_ride,first_lat,first_lng,pct_january,pct_jan1416
0,2112 W Peterson Ave,723,11,0,2023-02-02,2024-01-28,41.991028,-87.683748,18.257261,0.000000
1,410,7,0,0,2023-04-27,2023-04-27,41.900000,-87.690000,0.000000,0.000000
2,63rd St Beach,985,6,0,2023-02-12,2024-01-29,41.780818,-87.576407,7.309645,0.000000
3,900 W Harrison St,12646,449,4,2023-02-01,2024-01-31,41.842626,-87.704151,42.606358,0.379567
4,Aberdeen St & Jackson Blvd,14926,544,14,2023-02-01,2024-01-31,41.869211,-87.713046,43.735763,1.125553
...,...,...,...,...,...,...,...,...,...,...
1592,Woodlawn Ave & 58th St,2963,362,17,2023-09-15,2024-01-31,41.788912,-87.597045,146.608167,6.884914
1593,Woodlawn Ave & 75th St,105,4,0,2023-02-05,2024-01-22,41.759146,-87.595829,45.714286,0.000000
1594,Woodlawn Ave & Lake Park Ave,1597,57,1,2023-02-02,2024-01-31,41.813871,-87.597116,42.830307,0.751409
1595,Yates Blvd & 75th St,247,15,2,2023-02-11,2024-01-31,41.758655,-87.566511,72.874494,9.716599
1596,Yates Blvd & 93rd St,56,0,0,2023-02-15,2023-12-20,41.726134,-87.566448,0.000000,0.000000

### filter dataset to include only frequently-used stations

In [31]:
df_stations_large = df_stations[df_stations['rides_all']>=1000]

### top stations

In [32]:
df_stations_large.sort_values('pct_january',ascending=False)

,start_station_name,rides_all,rides_january,rides_jan14_16,first_ride,last_ride,first_lat,first_lng,pct_january,pct_jan1416
59,Blackstone Ave & 59th St,4463,634,17,2023-09-14,2024-01-31,41.787443,-87.628028,170.468295,4.570916
267,Drexel Ave & 60th St,1990,250,6,2023-08-03,2024-01-31,41.785453,-87.604868,150.753769,3.618090
1592,Woodlawn Ave & 58th St,2963,362,17,2023-09-15,2024-01-31,41.788912,-87.597045,146.608167,6.884914
1495,University Ave & 59th St,2698,293,1,2023-08-29,2024-01-31,41.787533,-87.599454,130.318755,0.444774
1507,W Washington Blvd & N Peoria St,1501,100,0,2023-05-25,2024-01-30,41.882835,-87.650308,79.946702,0.000000
...,...,...,...,...,...,...,...,...,...,...
271,DuSable Lake Shore Dr & North Blvd,35874,138,1,2023-02-01,2024-01-31,41.733342,-87.677964,4.616157,0.033450
312,Fort Dearborn Dr & 31st St,4941,18,0,2023-02-03,2024-01-29,41.838374,-87.680184,4.371585,0.000000
509,Lincoln Ave & Belmont Ave (Temp),3545,0,0,2023-02-01,2023-07-10,41.883602,-87.671937,0.000000,0.000000
80,Buckingham Fountain (Temp),4547,0,0,2023-06-06,2023-09-20,41.864012,-87.629385,0.000000,0.000000
614,Noble St & Milwaukee Ave (Temp),2038,0,0,2023-08-16,2023-11-15,41.883816,-87.662600,0.000000,0.000000

In [33]:
df_stations_large.sort_values('pct_jan1416',ascending=False)

,start_station_name,rides_all,rides_january,rides_jan14_16,first_ride,last_ride,first_lat,first_lng,pct_january,pct_jan1416
1592,Woodlawn Ave & 58th St,2963,362,17,2023-09-15,2024-01-31,41.788912,-87.597045,146.608167,6.884914
59,Blackstone Ave & 59th St,4463,634,17,2023-09-14,2024-01-31,41.787443,-87.628028,170.468295,4.570916
616,Normal Ave & Archer Ave,1277,81,4,2023-02-02,2024-01-31,41.849426,-87.640709,76.115897,3.758810
267,Drexel Ave & 60th St,1990,250,6,2023-08-03,2024-01-31,41.785453,-87.604868,150.753769,3.618090
118,Campbell Ave & Montrose Ave,3153,131,9,2023-02-01,2024-01-31,41.961040,-87.692321,49.857279,3.425309
...,...,...,...,...,...,...,...,...,...,...
313,Fort Dearborn Dr & 31st St*,3582,32,0,2023-06-05,2024-01-30,41.835238,-87.618259,10.720268,0.000000
312,Fort Dearborn Dr & 31st St,4941,18,0,2023-02-03,2024-01-29,41.838374,-87.680184,4.371585,0.000000
310,Field Museum,10590,66,0,2023-02-01,2024-01-31,41.847975,-87.666718,7.478754,0.000000
301,Evanston Civic Center,1431,53,0,2023-02-01,2024-01-31,42.056845,-87.686793,44.444444,0.000000
468,Lake Park Ave & 53rd St,6831,212,0,2023-02-01,2024-01-31,41.798203,-87.587036,37.241985,0.000000

In [34]:
df_stations_large.to_csv("../results/flourish-stations-january.csv", index=False)